### ISSUE TITLE
Site not live!

### ISSUE THREAD

**Issue by sydneyselch** [sydneyselch/lovenrevenge#1]
@thomasjbradley 

We changed all the info on Friday to get the site live, and he accepted the email and I committed and synced yesterday at 1pm and the site is still not live. Maybe it takes a bit over 24 hours and thats okay, but I just noticed something and wanted to make sure its okay. 

I looked on cloud flare to check and it says 'Please ensure your website is using the nameservers provided:' and has two hosts. Then I checked on the Merrit login page where the domain was hosted and the nameservers don't match. Is this supposed to be like this? Or should we have the nameservers match.. Maybe something didn't connect when we clicked okay. 

Please let me know asap!

![screen shot 2016-02-14 at 2 34 34 pm](https://cloud.githubusercontent.com/assets/6373190/13035938/b649c9da-d328-11e5-84e4-2b1eab739e7d.png)
![screen shot 2016-02-14 at 2 34 28 pm](https://cloud.githubusercontent.com/assets/6373190/13035937/b64911ca-d328-11e5-9d70-25a52dce4735.png)

**Comment by thomasjbradley** [comment]
Did you change the name servers again? And set the radio button to Use Custom Namerservers?
I did a look up and they are pointing properly to CloudFlare.

Seems to be working properly for me now... did you figure it out?

**Comment by sydneyselch** [comment]
Yeah I ended up changed the servers back and it worked! Something must have went wrong and it didnt accept when we hit okay before. I think I fully understand how all the servers work now from this issue though.
