### ISSUE TITLE
Google chrome cache not cleaning out. - still old site

### ISSUE THREAD

**Issue by sydneyselch** [sydneyselch/lovenrevenge#2]
The new site has updated on safari, firefox and any browser that has not seen the url before. But for any browser that has seen the URL, it is still the old URL. My client isn't able to view the site unless they download a new browser which is frustrating to them. 

Any idea how long the cache will stay like that? Or if there are any settings within the server settings where I can refresh the site for everyone.. Please let me know @thomasjbradley

**Comment by thomasjbradley** [comment]
You can try signing into CloudFlare and under the speed/performance section there's a clear all caches button you can try pressing.
